version: '3.7'

networks:
  auth_default:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-management/api:local
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - auth_default