"""init

Revision ID: f5bbf9c621ae
Revises: 6f189bd3f2b2
Create Date: 2021-08-27 10:14:16.453780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5bbf9c621ae'
down_revision = '6f189bd3f2b2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
