"""init

Revision ID: 548116feaf1e
Revises: f5bbf9c621ae
Create Date: 2021-08-27 10:17:11.099275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548116feaf1e'
down_revision = 'f5bbf9c621ae'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
